# The product of this Dockerfile has been pushed to:
# lfponcen/a_repo_space:0.1.0

FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive

COPY string_file /opt
CMD cat /opt/string_file; \
    echo "\nFor more information go to: \nhttps://github.com/luisfponce/iblodr"

